// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Card: typeof import('./src/components/Farm/Card.vue')['default']
    Farm: typeof import('./src/components/Farm/Farm.vue')['default']
    LoginDialog: typeof import('./src/components/LoginDialog.vue')['default']
    QAvatar: typeof import('quasar')['QAvatar']
    QBadge: typeof import('quasar')['QBadge']
    QBtn: typeof import('quasar')['QBtn']
    QCard: typeof import('quasar')['QCard']
    QCardActions: typeof import('quasar')['QCardActions']
    QCardSection: typeof import('quasar')['QCardSection']
    QChip: typeof import('quasar')['QChip']
    QCircularProgress: typeof import('quasar')['QCircularProgress']
    QDialog: typeof import('quasar')['QDialog']
    QExpansionItem: typeof import('quasar')['QExpansionItem']
    QHeader: typeof import('quasar')['QHeader']
    QIcon: typeof import('quasar')['QIcon']
    QImg: typeof import('quasar')['QImg']
    QInput: typeof import('quasar')['QInput']
    QItemSection: typeof import('quasar')['QItemSection']
    QLayout: typeof import('quasar')['QLayout']
    QLinearProgress: typeof import('quasar')['QLinearProgress']
    QPageContainer: typeof import('quasar')['QPageContainer']
    QSpace: typeof import('quasar')['QSpace']
    QTimeline: typeof import('quasar')['QTimeline']
    QTimelineEntry: typeof import('quasar')['QTimelineEntry']
    QToolbar: typeof import('quasar')['QToolbar']
    QToolbarTitle: typeof import('quasar')['QToolbarTitle']
    QTooltip: typeof import('quasar')['QTooltip']
    WorldTree: typeof import('./src/components/WorldTree.vue')['default']
  }
}

export { }
