// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    QBtn: typeof import('quasar')['QBtn']
    QCard: typeof import('quasar')['QCard']
    QCardActions: typeof import('quasar')['QCardActions']
    QCardSection: typeof import('quasar')['QCardSection']
    QDialog: typeof import('quasar')['QDialog']
    QHeader: typeof import('quasar')['QHeader']
    QInput: typeof import('quasar')['QInput']
    QLayout: typeof import('quasar')['QLayout']
    QPageContainer: typeof import('quasar')['QPageContainer']
    QSpace: typeof import('quasar')['QSpace']
    QToolbar: typeof import('quasar')['QToolbar']
    QToolbarTitle: typeof import('quasar')['QToolbarTitle']
  }
}

export {}
